FileVersion = 1
Dependencies = {corlib = "*", corlib = "*"}

[Project]
Name = "libclang-beef"
TargetType = "BeefLib"
StartupObject = "libclang_beef.Program"

[Configs.Debug.Win32]
LibPaths = ["$(ProjectDir)/deps/libclang.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/deps/libclang.dll\")"]

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/deps/libclang.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/deps/libclang.dll\")"]

[Configs.Release.Win32]
LibPaths = ["$(ProjectDir)/deps/libclang.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/deps/libclang.dll\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/deps/libclang.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/deps/libclang.dll\")"]

[Configs.Paranoid.Win32]
LibPaths = ["$(ProjectDir)/deps/libclang.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/deps/libclang.dll\")"]

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)/deps/libclang.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/deps/libclang.dll\")"]

[Configs.Test.Win32]
LibPaths = ["$(ProjectDir)/deps/libclang.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/deps/libclang.dll\")"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)/deps/libclang.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/deps/libclang.dll\")"]
